# Generated by Django 3.2.3 on 2021-08-18 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_alter_book_pages'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='isbn_10',
        ),
    ]
