# Generated by Django 3.2.3 on 2021-08-18 21:10

from django.db import migrations
import django_date_extensions.fields


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0008_auto_20210818_2109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='published_date',
            field=django_date_extensions.fields.ApproximateDateField(blank=True, null=True),
        ),
    ]
