# Generated by Django 3.2.3 on 2021-08-19 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0011_book_unique_joining'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='book',
            name='unique_joining',
        ),
        migrations.AddConstraint(
            model_name='book',
            constraint=models.UniqueConstraint(fields=('title', 'author', 'published_date', 'isbn_13', 'pages', 'publication_language'), name='unique_joining'),
        ),
    ]
