# Generated by Django 3.2.3 on 2021-08-20 14:57

import datetime
import django.core.validators
from django.db import migrations
import django_date_extensions.fields


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0012_auto_20210819_1040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='published_date',
            field=django_date_extensions.fields.ApproximateDateField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(limit_value=datetime.date.today)]),
        ),
    ]
