# Generated by Django 3.2.3 on 2021-08-26 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0014_auto_20210826_1500'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='authors',
        ),
        migrations.AlterField(
            model_name='author',
            name='name',
            field=models.CharField(max_length=256, unique=True),
        ),
    ]
