# Generated by Django 3.2.3 on 2021-08-27 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0018_auto_20210827_1016'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='book',
            name='unique_joining',
        ),
        migrations.AddConstraint(
            model_name='book',
            constraint=models.UniqueConstraint(fields=('title', 'published_date', 'isbn_13', 'pages', 'publication_language'), name='unique_joining'),
        ),
    ]
